import streamlit as st
import pandas as pd
from ortools.sat.python import cp_model
import os

# --- PAGE CONFIG ---
st.set_page_config(page_title="Nurse Assigner", layout="wide")

st.title("🏥 Nurse Assignment Auto-Scheduler")
st.markdown("Upload your **CSV** generated by the Excel Macro to generate assignments.")

# --- SIDEBAR SETTINGS ---
st.sidebar.header("⚙️ Optimization Settings")

# Weights
w_continuity = st.sidebar.slider("Prioritize Continuity", 0, 100, 50)
w_handoffs = st.sidebar.slider("Minimize Handoffs", 0, 100, 40)
w_acuity = st.sidebar.slider("Balance Acuity", 0, 100, 15)
w_charge_pref = st.sidebar.slider("Charge Nurse Protection", 0, 100, 100)

# Hard Limits
st.sidebar.markdown("---")
st.sidebar.header("🛑 Safety Limits")
limit_titratable = st.sidebar.number_input("Max Titratable Drips", 1, 5, 2)
limit_insulin = st.sidebar.number_input("Max Insulin Drips", 1, 2, 1)
limit_isolation = st.sidebar.number_input("Max Isolation Patients", 1, 4, 2)

# --- FILE UPLOAD ---
uploaded_file = st.file_uploader("Upload Input CSV", type=['csv'])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.write("### 📋 Data Preview")
    st.dataframe(df.head())

    # --- DETECT OFF-GOING CHARGE ---
    off_going_charge = "Unknown"
    if 'Off_Going_Charge' in df.columns:
        # Check the first row, handling potential NaNs
        val = df['Off_Going_Charge'].iloc[0]
        if pd.notna(val) and str(val).strip() != "":
            off_going_charge = str(val)
            st.success(f"✅ Detected Off-Going Charge: **{off_going_charge}**")
        else:
             st.warning("⚠️ Column found, but name is empty.")
             off_going_charge = st.text_input("Please enter Off-Going Charge Name manually:")
    else:
        st.warning("⚠️ 'Off_Going_Charge' column missing (Old Excel Template?).")
        off_going_charge = st.text_input("Please enter Off-Going Charge Name manually:")

    # --- RUN BUTTON ---
    if st.button("🚀 Generate Assignments"):
        if off_going_charge == "Unknown" or off_going_charge == "":
            st.error("Please enter an Off-Going Charge name to proceed.")
        else:
            with st.spinner("Optimizing Schedule... (This may take up to 60s)"):
                
                # ==========================================
                # LOGIC ENGINE (Your Tested Script)
                # ==========================================
                
                # 1. Setup
                nurses = df[['Nurse Name', 'Role', 'Max_Patients']].dropna(subset=['Nurse Name']).copy()
                nurses['Max_Patients'] = pd.to_numeric(nurses['Max_Patients'], errors='coerce').fillna(4).astype(int)
                nurses['Role'] = nurses['Role'].fillna('RN').astype(str)

                # Clean Patients
                cols_needed = {
                    'Room': str, 'Acuity_Score': int, 'Current_Nurse': str, 'Nurse_24hrs_Ago': str,
                    'Titratable_Gtt': int, 'Insulin_Gtt': int, 'Isolation': int, 'CiWA': int,
                    'Discharge_Planned': int, 'Transfer_Planned': int, 'Total_Care': int,
                    'New_Patient': int, 'Room Empty': int
                }
                
                def clean_input(val):
                    if pd.isnull(val): return 0
                    if isinstance(val, str):
                        val = val.strip().lower()
                        if val in ['yes', 'y', 'true', '1', 'new']: return 1
                        try: return int(float(val))
                        except: return 0
                    return int(val)

                patients = df.dropna(subset=['Room']).copy()
                for col, dtype in cols_needed.items():
                    patients.columns = [c.strip() for c in patients.columns]
                    if col not in patients.columns: patients[col] = 0
                    if col == 'Room': patients[col] = patients[col].astype(str)
                    elif col in ['Current_Nurse', 'Nurse_24hrs_Ago']: patients[col] = patients[col].fillna('Unknown').astype(str)
                    else: patients[col] = patients[col].apply(clean_input)

                # Sanitize Empty Rooms
                mask_empty = patients['Room Empty'] == 1
                patients.loc[mask_empty, ['Acuity_Score', 'Titratable_Gtt', 'Insulin_Gtt', 'Isolation', 'CiWA', 'Total_Care']] = 0
                
                # Handoff Setup
                off_going_nurses = patients['Current_Nurse'].unique()
                off_going_nurses = [n for n in off_going_nurses if n and str(n).lower() not in ['unknown', '0', 'nan']]

                # Model
                model = cp_model.CpModel()
                assignments = {}
                for n_idx, nurse in nurses.iterrows():
                    for p_idx, patient in patients.iterrows():
                        assignments[(n_idx, p_idx)] = model.NewBoolVar(f'n{n_idx}_p{p_idx}')

                # Constraints
                for p_idx in patients.index:
                    model.Add(sum(assignments[(n_idx, p_idx)] for n_idx in nurses.index) == 1)
                
                for n_idx, nurse in nurses.iterrows():
                    model.Add(sum(assignments[(n_idx, p_idx)] for p_idx in patients.index) <= int(nurse['Max_Patients']))
                    
                    # Clinical Totals
                    t_titr = sum(assignments[(n_idx, p_idx)] * patients.loc[p_idx, 'Titratable_Gtt'] for p_idx in patients.index)
                    t_ins = sum(assignments[(n_idx, p_idx)] * patients.loc[p_idx, 'Insulin_Gtt'] for p_idx in patients.index)
                    t_ciwa = sum(assignments[(n_idx, p_idx)] * patients.loc[p_idx, 'CiWA'] for p_idx in patients.index)
                    t_iso = sum(assignments[(n_idx, p_idx)] * patients.loc[p_idx, 'Isolation'] for p_idx in patients.index)
                    t_empty = sum(assignments[(n_idx, p_idx)] * patients.loc[p_idx, 'Room Empty'] for p_idx in patients.index)

                    if nurse['Role'].lower() == 'charge':
                        model.Add(t_empty == 0)
                        model.Add(t_titr == 0)
                        model.Add(t_ins == 0)
                        model.Add(t_ciwa == 0)
                    else:
                        model.Add(t_ins <= limit_insulin)
                        model.Add(t_titr + (10 * t_ins) <= 10)
                        model.Add(t_titr <= limit_titratable)
                        model.Add(t_ciwa <= 1)
                    
                    model.Add(t_iso <= limit_isolation)

                # Objectives
                objective_terms = []
                
                # Handoffs
                for n_idx, nurse in nurses.iterrows():
                    handoff_count_var = model.NewIntVar(0, len(off_going_nurses) + 1, f'handoffs_{n_idx}')
                    interactions = []
                    for off_nurse in off_going_nurses:
                        p_indices = patients[patients['Current_Nurse'] == off_nurse].index
                        has_interaction = model.NewBoolVar(f'interact_{n_idx}_{off_nurse}')
                        assigned_count = sum(assignments[(n_idx, p)] for p in p_indices)
                        model.Add(assigned_count > 0).OnlyEnforceIf(has_interaction)
                        model.Add(assigned_count == 0).OnlyEnforceIf(has_interaction.Not())
                        interactions.append(has_interaction)
                    model.Add(handoff_count_var == sum(interactions))
                    objective_terms.append(handoff_count_var * -w_handoffs)

                # Empty Room / Acuity / Conflicts
                for n_idx, nurse in nurses.iterrows():
                    expr_titr = sum(assignments[(n_idx, p_idx)] * patients.loc[p_idx, 'Titratable_Gtt'] for p_idx in patients.index)
                    expr_ins = sum(assignments[(n_idx, p_idx)] * patients.loc[p_idx, 'Insulin_Gtt'] for p_idx in patients.index)
                    expr_acuity = sum(assignments[(n_idx, p_idx)] * patients.loc[p_idx, 'Acuity_Score'] for p_idx in patients.index)
                    expr_empty = sum(assignments[(n_idx, p_idx)] * patients.loc[p_idx, 'Room Empty'] for p_idx in patients.index)
                    
                    # Fast Empty Logic
                    has_empty = model.NewBoolVar(f'has_empty_{n_idx}')
                    model.Add(expr_empty > 0).OnlyEnforceIf(has_empty)
                    model.Add(expr_empty == 0).OnlyEnforceIf(has_empty.Not())
                    
                    pen_acuity = model.NewIntVar(0, 200, f'pa_{n_idx}')
                    model.Add(pen_acuity == expr_acuity).OnlyEnforceIf(has_empty)
                    model.Add(pen_acuity == 0).OnlyEnforceIf(has_empty.Not())
                    objective_terms.append(pen_acuity * -50)

                    # Patient Logic
                    for p_idx, patient in patients.iterrows():
                        if nurse['Role'].lower() == 'charge':
                            if patient['Current_Nurse'] == off_going_charge:
                                if patient['Discharge_Planned'] == 1 or patient['Transfer_Planned'] == 1:
                                    objective_terms.append(assignments[(n_idx, p_idx)] * -50)
                                else:
                                    objective_terms.append(assignments[(n_idx, p_idx)] * w_charge_pref)
                            objective_terms.append(assignments[(n_idx, p_idx)] * int(patient['Acuity_Score']) * -5)
                            objective_terms.append(assignments[(n_idx, p_idx)] * int(patient['Isolation']) * -50)
                        else:
                            if patient['New_Patient'] == 0 and patient['Room Empty'] == 0:
                                if nurse['Nurse Name'] == patient['Nurse_24hrs_Ago']:
                                    objective_terms.append(assignments[(n_idx, p_idx)] * w_continuity)

                # Acuity Balance
                nurse_acuities = []
                for n_idx, nurse in nurses.iterrows():
                    total_acuity = sum(assignments[(n_idx, p_idx)] * int(patients.loc[p_idx, 'Acuity_Score']) for p_idx in patients.index)
                    nurse_acuities.append(total_acuity)
                min_a = model.NewIntVar(0, 100, 'min')
                max_a = model.NewIntVar(0, 100, 'max')
                model.AddMaxEquality(max_a, nurse_acuities)
                model.AddMinEquality(min_a, nurse_acuities)
                objective_terms.append((max_a - min_a) * -w_acuity)

                model.Maximize(sum(objective_terms))

                # Solve
                solver = cp_model.CpSolver()
                solver.parameters.max_time_in_seconds = 120.0
                status = solver.Solve(model)

                if status in [cp_model.OPTIMAL, cp_model.FEASIBLE]:
                    st.success(f"Solution Found! (Score: {solver.ObjectiveValue()})")
                    
                    results = []
                    for n_idx, nurse in nurses.iterrows():
                        p_list = []
                        sources = set()
                        vals = {'acuity':0, 'titr':0, 'ins':0, 'iso':0, 'ciwa':0, 'empty':0}
                        for p_idx, patient in patients.iterrows():
                            if solver.Value(assignments[(n_idx, p_idx)]) == 1:
                                lbl = patient['Room']
                                if patient['Room Empty']: 
                                    lbl += " (Empty)"
                                    vals['empty'] += 1
                                p_list.append(lbl)
                                
                                src = patient['Current_Nurse']
                                if src and str(src).lower() not in ['unknown', '0', 'nan']:
                                    sources.add(src)
                                    
                                vals['acuity'] += patient['Acuity_Score']
                                vals['titr'] += patient['Titratable_Gtt']
                                vals['ins'] += patient['Insulin_Gtt']
                                vals['iso'] += patient['Isolation']
                                vals['ciwa'] += patient['CiWA']
                        
                        results.append({
                            'Nurse': nurse['Nurse Name'],
                            'Role': nurse['Role'],
                            'Patients': ", ".join(p_list),
                            'Count': len(p_list),
                            'Total Acuity': vals['acuity'],
                            'Handoffs': len(sources),
                            'Report From': ", ".join(sorted(sources)),
                            'Drips (T/I)': f"{vals['titr']} / {vals['ins']}",
                            'CiWA': vals['ciwa'],
                            'Iso': vals['iso'],
                            'Empty': vals['empty']
                        })
                    
                    final_df = pd.DataFrame(results)
                    st.dataframe(final_df)
                    
                    # CSV Download
                    csv = final_df.to_csv(index=False).encode('utf-8')
                    st.download_button(
                        label="💾 Download Assignment Sheet",
                        data=csv,
                        file_name="Final_Shift_Assignments.csv",
                        mime="text/csv",
                    )

                else:
                    st.error("❌ No solution found. Try relaxing the safety limits in the sidebar.")
