import streamlit as st
import pandas as pd
import numpy as np
from ortools.sat.python import cp_model
from datetime import date
import io
import smtplib
from email.message import EmailMessage

# --- PAGE CONFIG ---
st.set_page_config(page_title="Nurse Assigner", layout="wide")
st.title("🏥 Nurse Assignment & Acuity Calculator")

# --- SIDEBAR ---
st.sidebar.header("📅 Shift Context")
assignment_date = st.sidebar.date_input("Assignment Date", date.today())
shift_type = st.sidebar.radio("Shift", ["Day", "Night"], horizontal=True)

st.sidebar.header("⚙️ Settings")
w_continuity = st.sidebar.slider("Prioritize Continuity", 0, 100, 50)
w_handoffs = st.sidebar.slider("Minimize Handoffs", 0, 100, 40)
w_acuity = st.sidebar.slider("Balance Workload", 0, 100, 25)
w_charge_pref = st.sidebar.slider("Charge Protection", 0, 100, 100)

st.sidebar.markdown("---")
st.sidebar.header("🛑 Limits")
limit_titratable = st.sidebar.number_input("Max Titratable Drips", 1, 5, 2)
limit_insulin = st.sidebar.number_input("Max Insulin", 1, 2, 1)
limit_restraints = st.sidebar.number_input("Max Restraints", 1, 3, 2)

# --- EMAIL FUNCTION ---
def send_email(recipient_email, file_buffer, filename):
    try:
        # Get credentials from Streamlit Secrets
        sender_email = st.secrets["email"]["sender_email"]
        sender_password = st.secrets["email"]["sender_password"]
        smtp_server = st.secrets["email"]["smtp_server"]
        smtp_port = st.secrets["email"]["smtp_port"]

        msg = EmailMessage()
        msg['Subject'] = f"Nurse Assignments - {assignment_date} ({shift_type})"
        msg['From'] = sender_email
        msg['To'] = recipient_email
        msg.set_content(f"Attached are the generated nurse assignments for {assignment_date} ({shift_type} shift).\n\nGenerated by the Nurse Assignment App.")

        # Attach file
        file_data = file_buffer.getvalue()
        msg.add_attachment(file_data, maintype='application', subtype='xlsx', filename=filename)

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
        
        return True, "Email sent successfully!"
    except Exception as e:
        return False, str(e)

# --- ACUITY CALCULATOR LOGIC ---
def calculate_acuity_score(row):
    if (row['O2_Device'] == 0) and (row['Med_Mgt'] == 0):
        return 3 

    current_max_level = 1
    o2_str = str(row['O2_Device']).lower()
    med_str = str(row['Med_Mgt']).lower()
    
    # Level 4
    if 'bipap' in o2_str or 'hiflow' in o2_str or 'high' in o2_str: return 4
    if row['Restraints'] == 1: return 4
    if row['Insulin_Gtt'] == 1: return 4
    if row['Titratable_Gtt'] == 1: return 4 
        
    # Level 3
    if 'mid' in o2_str or 'venti' in o2_str: current_max_level = max(current_max_level, 3)
    if row['Sitter'] == 1: current_max_level = max(current_max_level, 3)
    if row['Heparin_NonTher'] == 1: current_max_level = max(current_max_level, 3)
    if 'high' in med_str: current_max_level = max(current_max_level, 3)
    if row['DI_Score'] > 60: current_max_level = max(current_max_level, 3)

    # Level 2
    if 'nc' in o2_str or 'nasal' in o2_str: current_max_level = max(current_max_level, 2)
    if row['Heparin_Ther'] == 1: current_max_level = max(current_max_level, 2)
    if row['CiWA'] == 1: current_max_level = max(current_max_level, 2)
    if 'med' in med_str: current_max_level = max(current_max_level, 2)
    if row['DI_Score'] > 35: current_max_level = max(current_max_level, 2)

    return current_max_level

# --- DATA PREP ---
def preprocess_data(df, target_date, shift):
    df.columns = [str(c).strip() for c in df.columns]
    col_map = {
        'Nurse Name': 'Nurse Name', 'Role': 'Role', 'Max_Patients': 'Max_Patients',
        'Room': 'Room', 
        'Current_Nurse': 'Current_Nurse', 'Nurse_24hrs_Ago': 'Nurse_24hrs_Ago',
        'Titratable_Gtt': 'Titratable_Gtt', 'Insulin_Gtt': 'Insulin_Gtt', 
        'Isolation': 'Isolation', 'CiWA': 'CiWA', 'Total_Care': 'Total_Care',
        'Discharge_Planned': 'Discharge_Planned', 'Transfer_Planned': 'Transfer_Planned',
        'New_Patient': 'New_Patient', 'Room Empty': 'Room Empty',
        'Heparin_Gtt (Therapuetic)': 'Heparin_Ther',
        'Heparin_Gtt (Non-therapuetic)': 'Heparin_NonTher',
        'Supplmental_O2': 'O2_Device',
        'Med_Management': 'Med_Mgt',
        'Restraints': 'Restraints',
        'Sitter': 'Sitter',
        'Rapid_Response': 'Rapid_Response',
        'DI_Score': 'DI_Score',
        'Force_Assign': 'Force_Assign',
        'Avoid_Nurse': 'Avoid_Nurse'
    }
    
    clean = pd.DataFrame()
    for excel, internal in col_map.items():
        match = next((c for c in df.columns if excel.lower() in c.lower()), None)
        if match:
            clean[internal] = df[match]
        else:
            clean[internal] = 0 if internal not in ['O2_Device', 'Med_Mgt', 'Force_Assign', 'Avoid_Nurse', 'Nurse Name', 'Current_Nurse', 'Discharge_Planned'] else None

    binary_cols = ['Titratable_Gtt', 'Insulin_Gtt', 'Isolation', 'CiWA', 'Total_Care', 
                   'Transfer_Planned', 'New_Patient', 'Room Empty',
                   'Heparin_Ther', 'Heparin_NonTher', 'Restraints', 'Sitter', 'Rapid_Response']
    
    for c in binary_cols:
        clean[c] = clean[c].astype(str).apply(lambda x: 1 if x.strip().lower() in ['yes', 'y', '1', 'true'] else 0)

    clean['Discharge_Planned'] = pd.to_datetime(clean['Discharge_Planned'], errors='coerce').dt.date
    clean['Is_Active_DC'] = 0
    if shift == "Day":
        clean.loc[clean['Discharge_Planned'] == target_date, 'Is_Active_DC'] = 1
    
    clean['DI_Score'] = pd.to_numeric(clean['DI_Score'], errors='coerce').fillna(0)
    
    mask_reset = (clean['Room Empty'] == 1) | (clean['New_Patient'] == 1)
    clean['Calculated_Acuity'] = clean.apply(calculate_acuity_score, axis=1)
    
    if mask_reset.any():
        clean.loc[mask_reset, 'Calculated_Acuity'] = 3
        cols_to_wipe = ['Titratable_Gtt', 'Insulin_Gtt', 'Isolation', 'CiWA', 'Heparin_Ther', 'Restraints', 'DI_Score', 'Sitter', 'Rapid_Response']
        clean.loc[mask_reset, cols_to_wipe] = 0

    clean['Workload_Score'] = (
        clean['Calculated_Acuity'] + 
        (clean['DI_Score'] / 20.0) +
        (clean['Restraints'] * 0.5) + 
        (clean['Sitter'] * 0.5) +
        (clean['Rapid_Response'] * 2.0)
    )
    
    clean['Current_Nurse'] = clean['Current_Nurse'].fillna('Unknown')
    for c in ['Force_Assign', 'Avoid_Nurse']:
        clean[c] = clean[c].fillna('Unknown').astype(str)
            
    return clean

# --- APP ---
uploaded = st.file_uploader("Upload Input (.xlsx)", type=['xlsx', 'xlsm'])

if uploaded:
    raw = pd.read_excel(uploaded)
    df = preprocess_data(raw, assignment_date, shift_type)
    
    with st.expander("📋 Data Preview"):
        st.dataframe(df[['Room', 'Calculated_Acuity', 'Is_Active_DC', 'Discharge_Planned']])

    charges = [n for n in df['Current_Nurse'].unique() if str(n).lower() not in ['nan','0','unknown','']]
    charges.sort()
    off_going_charge = st.selectbox("Off-Going Charge:", options=charges, index=0 if charges else None)

    if st.button("🚀 Run Scheduler"):
        with st.spinner("Optimizing..."):
            nurses = df[['Nurse Name', 'Role', 'Max_Patients']].copy()
            nurses = nurses.dropna(subset=['Nurse Name'])
            nurses = nurses[nurses['Nurse Name'].astype(str).str.strip() != '']
            nurses = nurses[~nurses['Nurse Name'].astype(str).str.lower().isin(['nan', 'unknown', '0'])]
            
            nurses = nurses.drop_duplicates()
            nurses['Max_Patients'] = pd.to_numeric(nurses['Max_Patients'], errors='coerce').fillna(4).astype(int)
            nurses['Role'] = nurses['Role'].fillna('RN').astype(str)
            
            patients = df.dropna(subset=['Room']).copy()
            patients['Room'] = patients['Room'].astype(str)
            off_going_nurses = [n for n in patients['Current_Nurse'].unique() if str(n).lower() not in ['nan', 'unknown', '0']]

            if len(nurses) == 0:
                st.error("❌ No nurses found! Check columns A-D.")
                st.stop()

            model = cp_model.CpModel()
            x = {}
            for n in nurses.index:
                for p in patients.index:
                    x[n, p] = model.NewBoolVar(f'x_{n}_{p}')

            for p in patients.index:
                model.Add(sum(x[n, p] for n in nurses.index) == 1)

            for p, pat in patients.iterrows():
                force = str(pat['Force_Assign']).strip().lower()
                if force not in ['0', 'unknown', 'nan', '', 'none']:
                    target_nurse = next((n for n in nurses.index if force in str(nurses.loc[n, 'Nurse Name']).lower()), None)
                    if target_nurse is not None:
                        model.Add(x[target_nurse, p] == 1)
                    else:
                        st.warning(f"⚠️ Force Assign Failed: Nurse '{pat['Force_Assign']}' not found.")

                avoid = str(pat['Avoid_Nurse']).strip().lower()
                if avoid not in ['0', 'unknown', 'nan', '', 'none']:
                    target_nurse = next((n for n in nurses.index if avoid in str(nurses.loc[n, 'Nurse Name']).lower()), None)
                    if target_nurse is not None:
                        model.Add(x[target_nurse, p] == 0)

            objs = []
            nurse_dcs = []

            for n, nurse in nurses.iterrows():
                count = sum(x[n, p] for p in patients.index)
                t_titr = sum(x[n, p] * (patients.loc[p, 'Titratable_Gtt'] + patients.loc[p, 'Heparin_Ther']) for p in patients.index)
                t_ins = sum(x[n, p] * patients.loc[p, 'Insulin_Gtt'] for p in patients.index)
                t_iso = sum(x[n, p] * patients.loc[p, 'Isolation'] for p in patients.index)
                t_ciwa = sum(x[n, p] * patients.loc[p, 'CiWA'] for p in patients.index)
                t_empty = sum(x[n, p] * patients.loc[p, 'Room Empty'] for p in patients.index)
                t_rest = sum(x[n, p] * patients.loc[p, 'Restraints'] for p in patients.index)
                t_dc = sum(x[n, p] * patients.loc[p, 'Is_Active_DC'] for p in patients.index)
                
                nurse_dcs.append(t_dc) 

                has_insulin = model.NewBoolVar(f'has_ins_{n}')
                model.Add(t_ins > 0).OnlyEnforceIf(has_insulin)
                model.Add(t_ins == 0).OnlyEnforceIf(has_insulin.Not())
                model.Add(count <= 3).OnlyEnforceIf(has_insulin)

                roster_limit = int(nurse['Max_Patients'])
                model.Add(count <= 6)
                excess = model.NewIntVar(0, 6, f'excess_{n}')
                model.Add(excess >= count - roster_limit)
                model.Add(excess >= 0)
                objs.append(excess * -500)

                if str(nurse['Role']).lower() == 'charge':
                    model.Add(t_empty == 0)
                    model.Add(t_titr == 0)
                    model.Add(t_ins == 0)
                    model.Add(t_ciwa == 0)
                    model.Add(t_rest == 0)
                    model.Add(t_dc <= 1) 
                    objs.append(t_dc * -100)
                else:
                    model.Add(t_ins <= limit_insulin)
                    model.Add(t_titr + (10 * t_ins) <= 10)
                    model.Add(t_titr <= limit_titratable)
                    model.Add(t_ciwa <= 1)
                    model.Add(t_rest <= limit_restraints)
                
                model.Add(t_iso <= 2)

            min_dc = model.NewIntVar(0, 10, 'min_dc')
            max_dc = model.NewIntVar(0, 10, 'max_dc')
            model.AddMaxEquality(max_dc, nurse_dcs)
            model.AddMinEquality(min_dc, nurse_dcs)
            objs.append((max_dc - min_dc) * -50) 

            for n in nurses.index:
                ho = model.NewIntVar(0, 10, f'ho_{n}')
                interactions = []
                for off in off_going_nurses:
                    p_idx = patients[patients['Current_Nurse'] == off].index
                    active = model.NewBoolVar(f'act_{n}_{off}')
                    model.Add(sum(x[n, p] for p in p_idx) > 0).OnlyEnforceIf(active)
                    model.Add(sum(x[n, p] for p in p_idx) == 0).OnlyEnforceIf(active.Not())
                    interactions.append(active)
                model.Add(ho == sum(interactions))
                objs.append(ho * -w_handoffs)

                load = sum(x[n, p] * int(patients.loc[p, 'Workload_Score']*10) for p in patients.index)
                
                n_empty = sum(x[n, p] * patients.loc[p, 'Room Empty'] for p in patients.index)
                has_empty = model.NewBoolVar(f'he_{n}')
                model.Add(n_empty > 0).OnlyEnforceIf(has_empty)
                model.Add(n_empty == 0).OnlyEnforceIf(has_empty.Not())
                
                pen = model.NewIntVar(0, 5000, f'pen_{n}')
                model.Add(pen == load).OnlyEnforceIf(has_empty)
                model.Add(pen == 0).OnlyEnforceIf(has_empty.Not())
                objs.append(pen * -50)

                for p, pat in patients.iterrows():
                    if str(nurses.loc[n, 'Role']).lower() == 'charge':
                        if pat['Current_Nurse'] == off_going_charge and pat['Is_Active_DC']==0:
                            objs.append(x[n, p] * w_charge_pref)
                        objs.append(x[n, p] * int(pat['Workload_Score']*10) * -5)
                    else:
                        if pat['New_Patient']==0 and pat['Room Empty']==0:
                            if nurses.loc[n, 'Nurse Name'] == pat['Nurse_24hrs_Ago']:
                                objs.append(x[n, p] * w_continuity)
            
            nurse_loads = []
            for n in nurses.index:
                l = sum(x[n, p] * int(patients.loc[p, 'Workload_Score']*10) for p in patients.index)
                nurse_loads.append(l)
            mn = model.NewIntVar(0, 5000, 'min')
            mx = model.NewIntVar(0, 5000, 'max
