import streamlit as st
import pandas as pd
import numpy as np
from ortools.sat.python import cp_model
from datetime import date
import io
import smtplib
from email.message import EmailMessage

# --- PAGE CONFIG ---
st.set_page_config(page_title="Nurse Assigner", layout="wide")
st.title("🏥 Nurse Assignment & Acuity Calculator")

# --- SIDEBAR ---
st.sidebar.header("📅 Shift Context")
assignment_date = st.sidebar.date_input("Assignment Date", date.today())
shift_type = st.sidebar.radio("Shift", ["Day", "Night"], horizontal=True)

st.sidebar.header("⚙️ Settings")
w_continuity = st.sidebar.slider("Prioritize Continuity", 0, 100, 50)
w_handoffs = st.sidebar.slider("Minimize Handoffs", 0, 100, 40)
w_acuity = st.sidebar.slider("Balance Workload", 0, 100, 25)
w_charge_pref = st.sidebar.slider("Charge Protection", 0, 100, 100)

st.sidebar.markdown("---")
st.sidebar.header("🛑 Limits")
limit_titratable = st.sidebar.number_input("Max Titratable Drips", 1, 5, 2)
limit_insulin = st.sidebar.number_input("Max Insulin", 1, 2, 1)
limit_restraints = st.sidebar.number_input("Max Restraints", 1, 3, 2)

# --- EMAIL FUNCTION ---
def send_email(recipient_email, file_buffer, filename):
    try:
        # Get credentials from Streamlit Secrets
        sender_email = st.secrets["email"]["sender_email"]
        sender_password = st.secrets["email"]["sender_password"]
        smtp_server = st.secrets["email"]["smtp_server"]
        smtp_port = st.secrets["email"]["smtp_port"]

        msg = EmailMessage()
        msg['Subject'] = f"Nurse Assignments - {assignment_date} ({shift_type})"
        msg['From'] = sender_email
        msg['To'] = recipient_email
        msg.set_content(f"Attached are the generated nurse assignments for {assignment_date} ({shift_type} shift).\n\nGenerated by the Nurse Assignment App.")

        # Attach file
        file_data = file_buffer.getvalue()
        msg.add_attachment(file_data, maintype='application', subtype='xlsx', filename=filename)

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
        
        return True, "Email sent successfully!"
    except Exception as e:
        return False, str(e)

# --- ACUITY CALCULATOR LOGIC ---
def calculate_acuity_score(row):
    if (row['O2_Device'] == 0) and (row['Med_Mgt'] == 0):
        return 3 

    current_max_level = 1
    o2_str = str(row['O2_Device']).lower()
    med_str = str(row['Med_Mgt']).lower()
    
    # Level 4
    if 'bipap' in o2_str or 'hiflow' in o2_str or 'high' in o2_str: return 4
    if row['Restraints'] == 1: return 4
    if row['Insulin_Gtt'] == 1: return 4
    if row['Titratable_Gtt'] == 1: return 4 
        
    # Level 3
    if 'mid' in o2_str or 'venti' in o2_str: current_max_level = max(current_max_level, 3)
    if row['Sitter'] == 1: current_max_level = max(current_max_level, 3)
    if row['Heparin_NonTher'] == 1: current_max_level = max(current_max_level, 3)
    if 'high' in med_str: current_max_level = max(current_max_level, 3)
    if row['DI_Score'] > 60: current_max_level = max(current_max_level, 3)

    # Level 2
    if 'nc' in o2_str or 'nasal' in o2_str: current_max_level = max(current_max_level, 2)
    if row['Heparin_Ther'] == 1: current_max_level = max(current_max_level, 2)
    if row['CiWA'] == 1: current_max_level = max(current_max_level, 2)
    if 'med' in med_str: current_max_level = max(current_max_level, 2)
    if row['DI_Score'] > 35: current_max_level = max(current_max_level, 2)

    return current_max_level

# --- DATA PREP ---
def preprocess_data(df, target_date, shift):
    df.columns = [str(c).strip() for c in df.columns]
    col_map = {
        'Nurse Name': 'Nurse Name', 'Role': 'Role', 'Max_Patients': 'Max_Patients',
        'Room': 'Room', 
        'Current_Nurse': 'Current_Nurse', 'Nurse_24hrs_Ago': 'Nurse_24hrs_Ago',
        'Titratable_Gtt': 'Titratable_Gtt', 'Insulin_Gtt': 'Insulin_Gtt', 
        'Isolation': 'Isolation', 'CiWA': 'CiWA', 'Total_Care': 'Total_Care',
        'Discharge_Planned': 'Discharge_Planned', 'Transfer_Planned': 'Transfer_Planned',
        'New_Patient': 'New_Patient', 'Room Empty': 'Room Empty',
        'Heparin_Gtt (Therapuetic)': 'Heparin_Ther',
        'Heparin_Gtt (Non-therapuetic)': 'Heparin_NonTher',
        'Supplmental_O2': 'O2_Device',
        'Med_Management': 'Med_Mgt',
        'Restraints': 'Restraints',
        'Sitter': 'Sitter',
        'Rapid_Response': 'Rapid_Response',
        'DI_Score': 'DI_Score',
        'Force_Assign': 'Force_Assign',
        'Avoid_Nurse': 'Avoid_Nurse'
    }
    
    clean = pd.DataFrame()
    for
